---
- name: Configure Nginx with SSL
  hosts: web_servers
  become: true
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
    - name: Install SSL Certificates
      apt:
        name: certbot
        state: present
    - name: Obtain SSL Certificates
      command: certbot --nginx
