---
- name: Install Postfix Mail Server
  hosts: mail_servers
  become: true
  tasks:
    - name: Install Postfix
      apt:
        name: postfix
        state: present
    - name: Start Postfix
      service:
        name: postfix
        state: started
